### ISSUE TITLE
so i got it running but it crashes when i do !songs 

### ISSUE THREAD

**Issue by PlushBanshee** [TheBlackParrot/discord-midi-bot#9]
https://i.imgur.com/oZy0Y3p.png
https://i.imgur.com/pCbdrXp.png

**Comment by PlushBanshee** [comment]
update i got it to not crash
https://i.imgur.com/MsPGd5H.png
but it now says theres no songs and i cant join vc when i do radio on

**Comment by TheBlackParrot** [comment]
you're placing midi files in your midi folder right? and you being unable to join a voice channel sounds like a permission problem. running the bot shouldn't be preventing you from joining a voice channel.

if you meant the bot being unable to, i'd expect it not to be able to join if no midi files are present.i imagine it actually crashes instead.

**Comment by TheBlackParrot** [comment]
you're also running windows and i have yet to test to see if it even works in windows

**Comment by PlushBanshee** [comment]
yer it crashes and im a windows user

**Comment by PlushBanshee** [comment]
@TheBlackParrot i got the bot running on linux and still get the problem what OS are you running it on?

-i keep getting unable to load requests, using blank object 
-logs in
-i use a command

-D:\Bots\discord-midi-bot-master\server.js:123
                                        var attachment = new discord.MessageAttachment(Buffer.from(files.join("\r
\n")), "soundfonts" + Date.now() + ".txt");
                                                                                                        ^

TypeError: Cannot read property 'join' of undefined
    at D:\Bots\discord-midi-bot-master\server.js:123:70
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by TheBlackParrot** [comment]
have you defined where your soundfont folder is in settings.json, and does your soundfont folder exist? do you have permission to read said folder?

**Comment by PlushBanshee** [comment]
yep i do
"midi_folder": "/srv/code/discord-midi-bot/midi/",
	"soundfont_folder": "/srv/code/discord-midi-bot/sf2/",
	"default_soundfont": "1CreativeLabsSoundBlaster16ISA.sf2",
	"presets_folder": "/srv/code/discord-midi-bot/presets/",

**Comment by PlushBanshee** [comment]
now i does this 
```
/home/plush/discord-midi-bot/server.js:722
        if(!msg.member.voice.channel) {
                             ^

TypeError: Cannot read property 'channel' of undefined
    at playMIDI (/home/plush/discord-midi-bot/server.js:722:23)
    at parseCommand (/home/plush/discord-midi-bot/server.js:189:5)
    at Client.<anonymous> (/home/plush/discord-midi-bot/server.js:667:3)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/home/plush/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/plush/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/plush/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/plush/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/plush/node_modules/ws/lib/event-target.js:120:16)

**Comment by TheBlackParrot** [comment]
this whole system would require a rewrite at this point; discord.js has changed significantly. this repository is largely unmaintained.
you're better off converting your midi files to OGG or another lossy codec for use with other bots.
